### ISSUE TITLE
Wit.ai sync end point

### ISSUE THREAD

**Issue by julianaunion** [fczuardi/calamarcopolo-training#1]
Hi there,

I was pointed to this script by someone at Wit when asking about training the entities from the API. Would you be able to tell me about the`https://api.wit.ai/sync` endpoint? 

It is not in the [documentation](https://wit.ai/docs/http/20160330) of endpoints. 

Thanks for the help!

**Comment by fczuardi** [comment]
Hi,

There is not much to tell about it, I just copied what the browser does when you use the web interface to create or update entities, this endpoint is undocumented indeed :(

If you need help with my hackish shell script please let me know and maybe I can try to give you some directions, the WIT_BROWSER_TOKEN variable for example, is something you have to copy paste from some call made by your browser, it is different from the WIT_TOKEN that we have from the settings page.

**Comment by julianaunion** [comment]
Got it. That makes sense.

Thanks for your help. I should be able to figure out the script, I'll also take a look at the browser console - this was going to be my next step anyway haha. 

The reason I asked is because I wanted to train the keyword entities using the API. Someone at wit said this was supported, but cannot find any documentation on this either. Do you know anything about training the keyword entities vs. the traits? I figure I should be able to use a similar hack. 

Thanks again!

**Comment by julianaunion** [comment]
Actually if you could tell me where the WIT_BROWSER_TOKEN can be found, that would be helpful

**Comment by fczuardi** [comment]
on Chrome, deveoper tools, "Network" tab, you can copy the browser token here:

![screen shot 2016-05-06 at 2 38 42 pm](https://cloud.githubusercontent.com/assets/7760/15081325/de8db446-1398-11e6-8b12-b60f8fd26a7a.png)

In the place of the red rectangle .

**Comment by julianaunion** [comment]
Oh, I was just looking there. I assumed that was my WIT_TOKEN. Good to know that the  server access token for the application doesn't appear in the browser! i was getting worried about Wit's security protocols. Thanks!

**Comment by fczuardi** [comment]
> Do you know anything about training the keyword entities vs. the traits?

As far as I can tell, the main difference between training keyword entities vs traits is that with keywords you have to pass `start` and `end` parameters, with the position of the word in the phrase, for example, to train `arraial do cabo` in the expression `uma passagem para arraial do cabo`, the curl call is something along the lines:

``` sh
curl 'https://api.wit.ai/sync' -X PUT \
-H "Authorization: Bearer $WIT_BROWSER_TOKEN" \
-H 'Content-Type: application/json' \
-H "X-Wit-Instance: $WIT_APP_ID" \
-H 'DNT: 1' \
--data-binary '[{
    "data":{
        "text":{
            "text":"uma passagem para arraial do cabo"
        },
        "semantic":{
            "intent":"'"$INTENTID"'",
            "entities":[{
                "value":"Arraial do Cabo",
                "start":18,
                "end":33,
                "wisp":"'"$EntityID"'",
                "role":"destination"
            }]
        }
    },
    "type":"added-semantic"
}]' --compressed
```

**Comment by julianaunion** [comment]
Few more Qs - bit confused if you are training an entity for the first time, where does the $INTENTID come from? This assumed to already be initialized? Do you use the same intent generated in the UI for training all entities?

**Comment by fczuardi** [comment]
$INTENTID on this current version of wit is always the default_intent AFAIK, you can find it with https://wit.ai/docs/http/20160330#intents-index-link

**Comment by fczuardi** [comment]
yes, same intent for all entities

**Comment by julianaunion** [comment]
Got it. thank you. this will save a lot of time.

**Comment by l5t** [comment]
Sorry for the confusion. We are transitioning to a new model with Bot Engine Beta hence some gap in our documentation/API.
- You can train a keyword entity via https://wit.ai/docs/http/20160330#create-entity-value-link
- You cannot use our HTTP API to train a "trait" or "free-text" entity currently. You will have to rely on hacking the /sync like @fczuardi kindly exposes here.

This is in our roadmap though and we expect to support this directly from the API

**Comment by julianaunion** [comment]
Hey Laurent @l5t , 

Thanks for clarifying. Just to clear up the confusion I'm having -- I'm not seeing how the keyword entities are trained in that [create method](https://wit.ai/docs/http/20160330#create-entity-value-link) above.

If I create an entity then add a value to the entity, with an expressions list as in the doc:

```
$ curl -XPOST 'https://api.wit.ai/entities?v=20141022' \
-H "Authorization: Bearer $TOKEN" \
-H 'Content-Type: application/json' \
-d '{"id":"neighborhood"}'

$ curl -XPOST 'https://api.wit.ai/entities/neighborhood/values?v=20141022' \
-H "Authorization: Bearer $TOKEN" \
-H 'Content-Type: application/json' \
-d '{"value":"812","metadata":"{\"station_id\": 52817}","expressions":["Puerta de Tierra"]}'

```

```
$ curl -XGET 'https://api.wit.ai/message?v=20141022&q=Puerta%20de%20Tierra' \
-H "Authorization: Bearer $TOKEN"
```

Sending the text query above of text from the expression's list of the new entity yields this response:

> {
>   "msg_id" : "0d5cd325-5e24-4ceb-ab0b-03f28a3dfccf",
>   "_text" : "Puerta de Tierra",
>   "outcomes" : [ {
>     "_text" : "Puerta de Tierra",
>     "confidence" : null,
>     "intent" : "default_intent",
>     "entities" : { }
>   } ]
> }

However, by using the sync endpoint and calling:

```
$ curl 'https://api.wit.ai/sync' -X PUT \
-H "Authorization: Bearer $WIT_BROWSER_TOKEN" \
-H 'Content-Type: application/json' \
-H "X-Wit-Instance: $WIT_APP_ID" \
-H 'DNT: 1' \
--data-binary '[{
    "data":{
        "text":{
            "text":"Puerta de Tierra"
        },
        "semantic":{
            "intent":"'"$INTENTID"'",
            "entities":[{
                "value":"812",
                "start":0,
                "end":16,
                "wisp":"'"$EntityID"'",
                "role":"destination"
            }]
        }
    },
    "type":"added-semantic"
}]' --compressed

```

The same text query gives me the desired response below:

> { "msg_id" : "87c29ee0-ee63-4d20-8660-622317db2d94",
>   "_text" : "Puerta de Tierra",
>   "outcomes" : [ {
>     "_text" : "Puerta de Tierra",
>     "confidence" : null,
>     "intent" : "default_intent",
>     "entities" : {
>       "destination" : [ {
>         "metadata" : "{\"station_id\": 52817}",
>         "type" : "value",
>         "value" : "812" } ] 
> }} 
> ]}

LMK if I'm missing something.

**Comment by l5t** [comment]
I see, it's because we don't trigger the training when you use the API to create/update the training dataset

**Comment by l5t** [comment]
FYI, we released a new version of the API and docs. You can now train a keyword or trait entity via https://wit.ai/docs/http/20160526#post--entities-link

**Comment by fczuardi** [comment]
cool! I think I may close this issue already :) thanks!
